version: "3.5"
services:

  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
    volumes:
      - /mnt/pool/docker/misc/autobrr:/config   # updated

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
    volumes:
      - /mnt/pool/docker/misc/prowlarr:/config  # updated
    ports:
      - 9696:9696
    restart: always

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    ports:
      - 8191:8191
    restart: always

  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr
    ports:
      - "6969:6969"
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /mnt/pool/docker/misc/whisparr:/config  # updated
      - /mnt/pool/data:/data

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
    volumes:
      - /mnt/pool/docker/sonarr:/config         # updated
      - /mnt/pool/data:/data
    ports:
      - 8989:8989
    restart: always

  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
    volumes:
      - /mnt/pool/docker/radarr:/config         # updated
      - /mnt/pool/data:/data
    ports:
      - 7878:7878
    restart: always

  nzbget:
    image: ghcr.io/hotio/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
    volumes:
      - /mnt/pool/docker/misc/nzbget:/config    # updated
      - /mnt/pool/data/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
      - VERSION=latest
      - PLEX_CLAIM=claim-Zs2Sx3gNxmC8KXVQHx72
    volumes:
      - /mnt/pool/docker/plex:/config           # updated
      - /tmp/transcode:/transcode
      - /mnt/pool/data/Media:/data2
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      TZ: America/Detroit
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "false"
      WATCHTOWER_SCHEDULE: 0 30 0 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
