version: "3.5"
services:

  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 256m
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
    volumes:
      - /mnt/nvmepool/docker/misc/autobrr:/config
    ports:
      - 7474:7474

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: always
    mem_limit: 1g
    mem_reservation: 256m
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
    volumes:
      - /mnt/nvmepool/docker/misc/prowlarr:/config
    ports:
      - 9696:9696

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: always
    mem_limit: 1g
    mem_reservation: 256m
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    ports:
      - 8191:8191

  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr
    mem_limit: 1g
    mem_reservation: 256m
    ports:
      - "6969:6969"
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /mnt/nvmepool/docker/misc/whisparr:/config
      - /mnt/pool/data:/data

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    restart: always
    mem_limit: 1g
    mem_reservation: 256m
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
    volumes:
      - /mnt/nvmepool/docker/sonarr:/config
      - /mnt/pool/data:/data
    ports:
      - 8989:8989

  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    restart: always
    mem_limit: 1g
    mem_reservation: 256m
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
    volumes:
      - /mnt/nvmepool/docker/radarr:/config
      - /mnt/pool/data:/data
    ports:
      - 7878:7878

  nzbget:
    image: ghcr.io/hotio/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 256m
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
    volumes:
      - /mnt/nvmepool/docker/misc/nzbget:/config
      - /mnt/pool/data/downloads:/downloads
    ports:
      - 6789:6789

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    mem_limit: 8g
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
      - VERSION=latest
      - PLEX_CLAIM=claim-Zs2Sx3gNxmC8KXVQHx72
    volumes:
      - /mnt/nvmepool/docker/plex:/config
      - /tmp/transcode:/transcode
      - /mnt/pool/data/Media:/data2
    devices:
      - /dev/dri:/dev/dri
    network_mode: host

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    mem_limit: 1g
    mem_reservation: 256m
    environment:
      TZ: America/Detroit
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "false"
      WATCHTOWER_SCHEDULE: 0 30 0 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
