---
version: "2.4"
services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr-mediamgmt
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
    volumes:
      - /mnt/ssdpool/docker/volumes/prowlarr/_data:/config
    ports:
      - 9696:9696
    restart: always
  
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr-mediamgmt
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    ports:
      - "${PORT:-8191}:8191"
    restart: always 
 
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr-mediamgmt
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
    volumes:
      - /mnt/ssdpool/docker/volumes/sonarr/_data:/config
      - /mnt/pool/data:/truenasdata
      - /mnt/Home_Data:/data
    ports:
      - 8989:8989
    restart: always

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr-mediamgmt
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
    volumes:
      - /mnt/ssdpool/docker/volumes/radarr/_data:/config
      - /mnt/pool/data:/truenasdata
      - /mnt/Home_Data:/data
    ports:
      - 7878:7878
    restart: always



volumes:
  sonarr:
    name: sonarr
    driver: local-persist
    driver_opts:
      mountpoint: /ssdpool/docker/volumes/sonarr/_data 
  radarr:
    name: radarr
    driver: local-persist
    driver_opts:
      mountpoint: /ssdpool/docker/volumes/radarr/_data
  prowlarr:
    name: prowlarr
    driver: local-persist
    driver_opts:
      mountpoint: /ssdpool/docker/volumes/prowlarr/_data   

